module.exports = [
    require('./GraphqlModels/catagory'),
    require('./GraphqlModels/certificate_name'),
    require('./GraphqlModels/certificates'),
    require('./GraphqlModels/coaches'),
    require('./GraphqlModels/course_field_value'),
    require('./GraphqlModels/courses'),
    require('./GraphqlModels/courses_fields'),
    require('./GraphqlModels/courses_name'),
    require('./GraphqlModels/fields_certificate_lookup'),
    require('./GraphqlModels/certificate_fields_tags'),
    require('./GraphqlModels/lang_sex'),
    // require('./GraphqlModels/print_course_student'),
    require('./GraphqlModels/profiles'),
    // require('./GraphqlModels/reset_passwords'),
    require('./GraphqlModels/roles'),
    require('./GraphqlModels/smbs_certificate_lookup'),
    require('./GraphqlModels/smbs_name'),
    require('./GraphqlModels/stamps_marks_backgrounds_signatures'),
    require('./GraphqlModels/student_fields_course_value'),
    require('./GraphqlModels/students'),
    require('./GraphqlModels/texts'),
    require('./GraphqlModels/users')
]
